# Generated by Django 4.2.23 on 2025-08-23 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sample_type', models.CharField(default='blood', max_length=50)),
                ('collected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('received', 'received'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='received', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('analyte', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=20)),
                ('ref_low', models.FloatField(blank=True, null=True)),
                ('ref_high', models.FloatField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.sample')),
            ],
        ),
    ]
